title: Yannan Su # your name (or website title) here
logo: "/images/web_profile_2.jpeg?raw=true" # your photo (or logo) here
# logo: <img src="/images/profile-pic.jpg"
#      width="400" 
#      height="500" />
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Enthusiast, Computational Neuroscientist
  <br><br>
  More About Me:
  <br><br>
   CV | <a href="https://www.linkedin.com/in/yannan-su">LinkedIn</a> | <a href="https://sodabubbles.netlify.app">Digital Garden</a> 
  <br><br>
  In my spare time, I take <a href=" https://www.instagram.com/soda_moments">photos</a>, read <a href="https://words-in-world.vercel.app">books</a> , and write <a href="https://7nothingspecial7.wordpress.com">blog in Chinese</a>.  
  

  
theme: jekyll-theme-minimal
google_analytics:  # your Google Analytics tracking ID here
