title: Yannan Su # your name (or website title) here
logo: "/images/profile-pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Enthusiast 
  <br><br>
  Computational Neuroscientist
  <br><br>
  <a href="https://https://sodabubbles.netlify.app">My Digital Garden</a> 
  <br><br>
  <a href="https://7nothingspecial7.wordpress.com">My Blog (Chinese)</a> 

  
  
theme: jekyll-theme-minimal
google_analytics:  # your Google Analytics tracking ID here
