title: Yannan Su # your name (or website title) here
logo: "/images/web_profile_2.jpeg?raw=true" # your photo (or logo) here
# logo: <img src="/images/profile-pic.jpg"
#      width="400" 
#      height="500" />
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist | AI x Health Enthusiast 
  <br><br>
  Ph.D. in Computational Neuroscience
  <br><br>
  based in Germany  
  <br><br>
  now at  <a href="https://alpinelongevity.com">Alpine Institute</a>
  <br><br>
  More About Me:
  <a href="https://www.linkedin.com/in/yannan-su">LinkedIn</a>|<a href="https://scholar.google.com/citations?hl=en&user=FD3M8jEAAAAJ">GoogleScholar</a>|<a href="https://sodabubbles.netlify.app/">Digital Garden</a>
  <br><br>
  In my spare time, I take <a href=" https://www.instagram.com/soda_moments">photos</a>, read <a href="https://sodabubbles.netlify.app/index/some%20books%20i%20have%20read/">books</a> , and write <a href="https://7nothingspecial7.wordpress.com">blog in Chinese</a>.  
  

  
theme: jekyll-theme-minimal
google_analytics:  # your Google Analytics tracking ID here
